// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHxgW-4LGaZrGuvXKdWwKc7cK-XRmdX4o',
    appId: '1:163668155657:web:58fa5a672ef948fc6287d8',
    messagingSenderId: '163668155657',
    projectId: 'flutter-chat-app-1b007',
    authDomain: 'flutter-chat-app-1b007.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1b007.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmufkthOCpJOpORKQu1D8GUfJAhO3iuPo',
    appId: '1:163668155657:android:e2421e5dede555dd6287d8',
    messagingSenderId: '163668155657',
    projectId: 'flutter-chat-app-1b007',
    storageBucket: 'flutter-chat-app-1b007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCheMKxEu6odNYg1QsH_ckFGO-soGO0HA',
    appId: '1:163668155657:ios:14c811a6275bc3566287d8',
    messagingSenderId: '163668155657',
    projectId: 'flutter-chat-app-1b007',
    storageBucket: 'flutter-chat-app-1b007.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCheMKxEu6odNYg1QsH_ckFGO-soGO0HA',
    appId: '1:163668155657:ios:981992998931ad506287d8',
    messagingSenderId: '163668155657',
    projectId: 'flutter-chat-app-1b007',
    storageBucket: 'flutter-chat-app-1b007.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
